puts "New line after this\n"
puts "Double quote \"Your text"
puts "Single backslash \\"
puts "Alert \a"
puts "Backspace \b"
puts "Use it when you want to do tabulation \t space, like this"
puts "To make a space in the line, use \s. Pretty simple"
puts "To return the carriage, use \r"

puts "Vertical tab\v"
puts "Formfeed\f"
puts "Escape \e"
puts "Control-x \cx"
puts "Octal character \000"
puts "Hexadecimal character \x00"

puts "Unicode code point \u0000"
puts "Unicode code point with more than four hex digits\u{00000}"
puts "\""